version: 3.0.{Build}
environment:
  my_variable:
    secure: AKugtDtAqaxxFaTsJUT432knICglfZ8zmdeDuBZErS0A1GOnC1FaOizAJgM4pAUw
build_cloud: houstonlab
image: labwmf5
clone_folder: C:\projects\HPOneView.300
init:
- ps: $env:PSModulePath += ";C:\Projects"
build: off
test_script:
- ps: "Import-Module \"C:\\Tests\\appveyor.tests.ps1\"\nStart-PoshTest\nStart-PoshTest -Finalize\n\nUpdate-AppveyorBuild -Version $Global:Version"
notifications:
- provider: Email
  to:
  - chris.lynch@hpe.com
  - chris.lynch@outlook.com
  subject: 'POSH-HPOneView.300 AppVeyor Results {{status}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "chris.lynch@hpe.com"
  - git config --global user.name "Chris Lynch"
  - git tag v{version} -m "Release {version}"
  - git push origin v{version}