version: 3.0.{Build}
branches:
  only:
    - 3.00

skip_tags: true
build_cloud:
- doc-hyp-01

image: labwmf5
clone_folder: C:\projects\HPOneView.300

init:
- ps: $env:PSModulePath += ";C:\Projects"

environment:
  ACCESS_TOKEN:
    secure: QA6hiomS2Zz67tRQMLfMlYXsLioPZLO6q6NSxSctZU+TMT9sJvC+VlGfSO0bIb05

build: off
test_script:
- ps: >-

    Import-Module "C:\Tests\appveyor.tests.ps1"
    
    Start-PoshTest

notifications:
- provider: Email
  to:
    - chris.lynch@hpe.com
    - chris.lynch@outlook.com
  
  subject: POSH-HPOneView.300 AppVeyor Results
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
