version: 3.10.{build}
branches:
  only:
    - 3.10

skip_tags: true

skip_commits:
  files:
    - LICENSE
    - '*.psd1'
    - '**/*.xml'
    - '**/*.txt'
    - '*.md'
    - '*.yml'
    - .github/*.md

build_cloud:
- doc-hyp-02

image: labwmf5
clone_folder: C:\projects\HPOneView.310

init:
- ps: $env:PSModulePath += ";C:\Projects"

environment:
  ACCESS_TOKEN:
    secure: 2cM8izTtmmL7B0li5CCq5Qa63Yu9+VyIN2SHlNSOpEOSwKj0wpqb4aopMf4Fyu7X

build: off
test_script:
- ps: >-

    Import-Module "C:\Tests\appveyor.tests.ps1"

    Start-PoshTest

notifications:
- provider: Email
  to:
    - chris.lynch@hpe.com
    - chris.lynch@outlook.com

  subject: POSH-HPOneView.310 AppVeyor Results
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
