version: 4.00.{build}
branches:
  only:
  - 4.00
skip_tags: true
build_cloud: doc-hyp-01
image: labwmf5
clone_folder: C:\projects\HPOneView.400
init:
- ps: $env:PSModulePath += ";C:\Projects"
environment:
  ACCESS_TOKEN:
    secure: 2cM8izTtmmL7B0li5CCq5Qa63Yu9+VyIN2SHlNSOpEOSwKj0wpqb4aopMf4Fyu7X
build: off
test_script:
- ps: >-
    Import-Module "C:\Tests\appveyor.tests.ps1"

    Start-PoshTest
notifications:
- provider: Email
  to:
  - chris.lynch@hpe.com
  - chris.lynch@outlook.com
  subject: POSH-HPOneView.400 AppVeyor Results
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
on_success:
- ps: >-
    #push version tag to remote

    cd $env:APPVEYOR_BUILD_FOLDER

    git remote set-url origin "https://$($env:access_token):x-oauth-basic@github.com/HewlettPackard/POSH-HPOneView.git"

    git tag "v$env:APPVEYOR_BUILD_VERSION" -m "Release $env:APPVEYOR_BUILD_VERSION"

    git push origin "v$env:APPVEYOR_BUILD_VERSION"

skip_commits:
  files:
    - LICENSE
    - '*.psd1'
    - '**/*.xml'
    - '**/*.txt'
    - '*.md'
    - '*.yml'
    - .github/*.md


